INFO 2024-11-19 16:55:39,548 autoreload 38 137607100708672 Watching for file changes with StatReloader
ERROR 2024-11-19 16:55:49,996 log 38 137606914377472 Internal Server Error: /
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/debug_toolbar/middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/debug_toolbar/toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
ERROR 2024-11-19 16:55:49,998 basehttp 38 137606914377472 "GET / HTTP/1.1" 500 141185
INFO 2024-11-19 16:57:19,369 autoreload 38 137607100708672 /code/project/myshop/urls.py changed, reloading.
INFO 2024-11-19 16:57:20,690 autoreload 72 134343351187264 Watching for file changes with StatReloader
INFO 2024-11-19 16:57:23,674 autoreload 72 134343351187264 /code/project/myshop/settings.py changed, reloading.
INFO 2024-11-19 16:57:24,805 autoreload 87 126003132581696 Watching for file changes with StatReloader
INFO 2024-11-19 17:00:58,875 autoreload 38 127392923707200 Watching for file changes with StatReloader
INFO 2024-11-19 17:05:09,841 basehttp 38 127392739755776 "GET / HTTP/1.1" 200 9004
INFO 2024-11-19 17:05:09,870 basehttp 38 127392739755776 "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12621
INFO 2024-11-19 17:05:09,870 basehttp 38 127392727172864 "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13404
INFO 2024-11-19 17:05:09,878 basehttp 38 127392727172864 "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4527
INFO 2024-11-19 17:05:09,913 basehttp 38 127392739755776 "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
INFO 2024-11-19 17:05:18,410 basehttp 38 127392727172864 "GET / HTTP/1.1" 200 9002
